// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCsEhlEab6rSVRA1KlHm50G-utwKtPugs',
    appId: '1:2220485973:android:e7b1191b7b4fafad7dd3dc',
    messagingSenderId: '2220485973',
    projectId: 'g-chat-d1bcb',
    databaseURL: 'https://g-chat-d1bcb-default-rtdb.firebaseio.com',
    storageBucket: 'g-chat-d1bcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsl5qJK-FaBG_cDmnGxyDxafRlb553fLc',
    appId: '1:2220485973:ios:eadf6f5156fbe1b57dd3dc',
    messagingSenderId: '2220485973',
    projectId: 'g-chat-d1bcb',
    databaseURL: 'https://g-chat-d1bcb-default-rtdb.firebaseio.com',
    storageBucket: 'g-chat-d1bcb.firebasestorage.app',
    iosBundleId: 'com.example.gChat',
  );
}
